global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: mlops-network
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}

# Redirect HTTP to HTTPS
http:
  redirections:
    entrypoint:
      to: websecure
      scheme: https