# ansible/playbooks/04_install_docker.yml

---
- name: Install Docker and Docker Compose on VM Production
  hosts: infrastructure  # ใช้ Group ที่กำหนดใน hosts.yml
  become: yes            # จำเป็นต้องมีสิทธิ์ sudo ในการติดตั้ง
  gather_facts: yes

  tasks:
    - name: Install required system dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Engine and Compose v2
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add '{{ ansible_user }}' to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      # หมายเหตุ: User ต้อง Logout/Login ใหม่เพื่อให้สิทธิ์มีผล

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
